export const getAuthStrings = (t) => ({
  appName: t('auth.appName'),
  appTagline: t('auth.appTagline'),
  login: t('auth.login'),
  loginWithEmailCode: t('auth.loginWithEmailCode', {
    defaultValue: 'Sign in with email code',
  }),
  signUp: t('auth.signUp'),
  logout: t('auth.logout'),
  confirmLogout: t('auth.confirmLogout'),
  deleteAccount: t('auth.deleteAccount'),
  confirmDeleteAccount: t('auth.confirmDeleteAccount'),
  continue: t('auth.continue'),
  submit: t('auth.submit'),
  verify: t('auth.verify'),
  resendCode: t('auth.resendCode'),
  resendCooldown: (seconds) => t('auth.resendCooldown', { seconds }),
  cancel: t('common.cancel'),
  welcomeTitle: t('auth.welcomeTitle'),
  welcomeSubtitle: t('auth.welcomeSubtitle'),
  loginTitle: t('auth.loginTitle'),
  loginSubtitle: t('auth.loginSubtitle'),
  emailLabel: t('auth.emailLabel'),
  emailPlaceholder: t('auth.emailPlaceholder'),
  passwordLabel: t('auth.passwordLabel'),
  passwordPlaceholder: t('auth.passwordPlaceholder'),
  forgotPasswordLink: t('auth.forgotPasswordLink'),
  noAccountPrompt: t('auth.noAccountPrompt'),
  signUpTitle: t('auth.signUpTitle'),
  signUpSubtitle: t('auth.signUpSubtitle'),
  fullNameLabel: t('auth.fullNameLabel'),
  fullNamePlaceholder: t('auth.fullNamePlaceholder'),
  phoneLabel: t('auth.phoneLabel'),
  phonePlaceholder: t('auth.phonePlaceholder'),
  cityLabel: t('auth.cityLabel'),
  cityPlaceholder: t('auth.cityPlaceholder'),
  confirmPasswordLabel: t('auth.confirmPasswordLabel'),
  confirmPasswordPlaceholder: t('auth.confirmPasswordPlaceholder'),
  alreadyHaveAccount: t('auth.alreadyHaveAccount'),
  otpTitle: t('auth.otpTitle'),
  otpSubtitle: (email) => t('auth.otpSubtitle', { email }),
  enterOtpLabel: t('auth.enterOtpLabel'),
  otpPlaceholder: t('auth.otpPlaceholder'),
  otpExpired: t('auth.otpExpired'),
  otpSentSuccess: t('auth.otpSentSuccess'),
  forgotTitle: t('auth.forgotTitle'),
  forgotSubtitle: t('auth.forgotSubtitle'),
  resetTitle: t('auth.resetTitle'),
  resetSubtitle: t('auth.resetSubtitle'),
  newPasswordLabel: t('auth.newPasswordLabel'),
  newPasswordPlaceholder: t('auth.newPasswordPlaceholder'),
  errEmailRequired: t('auth.errEmailRequired'),
  errInvalidCredentials: t('auth.errInvalidCredentials', {
    defaultValue: 'Email or password is incorrect. If you have not set a password yet, use Forgot password to create one.',
  }),
  errPasswordMinLength: t('auth.errPasswordMinLength'),
  errPasswordMismatch: t('auth.errPasswordMismatch'),
  errFullNameRequired: t('auth.errFullNameRequired'),
  errOtpLength: t('auth.errOtpLength'),
  errGeneric: t('auth.errGeneric'),
});
